const COLORS = {
  biela: '#f5f5f5',
  cierna: '#111111',
  siva: '#888888',
  zlta: '#fffb00',
  cervena: '#e63030',
  modra: '#0057ff',
  oranzova: '#ff5c00',
  zelena: '#22c55e',
  fialova: '#7c3aed',
  svetlomodra: '#5b9fff',
  kremova: '#ede8d9',
  ruzova: '#f472b6',
};

const MODELS = [
  {
    id: 1,
    name: 'Monster Energy Pohar vyrezany',
    desc: 'Monster Energy pohár – vyrezávaný dizajn.',
    time: '2 dni',
    price: 'od 15€',
    size: '9×9×12cm',
    material: 'PLA',
    colors:  ['cierna', 'biela', 'zelena', 'ruzova', 'oranzova', 'zlta'],     
    image: 'https://i.ebayimg.com/images/g/xR8AAeSwUeVn98l6/s-l1200.jpg',  
  },
  {
    id: 2,
    name: 'Monster Energy Pohar plný',
    desc: 'Monster Energy pohár.',
    time: '2 dni',
    price: 'od 20€',
    size: '9×9×12cm',
    material: 'PLA',
    colors:  ['cierna', 'biela', 'zelena', 'ruzova', 'oranzova', 'zlta'],
    colors2: ['cierna', 'biela', 'zelena', 'ruzova', 'oranzova', 'zlta'],
    image: 'https://makerworld.bblmw.com/makerworld/model/1645823/1739497/ratings/2025-08-01_66edd74fb405a8.jpg',
  },
  {
    id: 3,
    name: 'Monster Energy uzáver na plechovku',
    desc: 'Uzáver na plechovku, nie je vodotesný.',
    time: '1 deň',
    price: 'od 6€',
    size: '9×9×12cm',
    material: 'PLA',
    colors:  ['cierna', 'biela', 'zelena', 'ruzova', 'oranzova', 'zlta'],
    colors2: ['cierna', 'biela', 'zelena', 'ruzova', 'oranzova', 'zlta'],
    image: '',
  },
];
